services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: https://awaken-api-4e511c3c-4cd9-46ae-8bfa-2ae44789e433.fly.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
